apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  type: LoadBalancer
  externalIPs:
  - 192.168.58.2
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8080